apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: omnitools
    namespace: omnitools
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '6.16.1'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "omnitools"
        deployment:
            enabled: true
            image:
                repository: iib0011/omni-tools
                tag: 0.6.0
            containerSecurityContext:
                    readOnlyRootFilesystem: false
                    runAsNonRoot: false
        service:
            enabled: true
            ports:
                - port: 8080
                  name: http
                  protocol: TCP
                  targetPort: 80
        ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
                traefik.ingress.kubernetes.io/router.middlewares: traefik-oidc@kubernetescrd
            hosts:
                - host: tools.bibletoon.xyz
                  paths:
                      - path: /