apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: s3-store
  namespace: freshrss
spec:
  configuration:
    destinationPath: s3://pg-backup/
    endpointURL: https://s3.biblenas.xyz
    s3Credentials:
      accessKeyId:
        name: s3-creds
        key: keyId
      secretAccessKey:
        name: s3-creds
        key: secretKey
      region:
        name: s3-creds
        key: region
    wal:
      compression: gzip
  retentionPolicy: "7d"
