apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: freshrss-postgres
    namespace: freshrss
spec:
    instances: 3
    storage:
        storageClass: longhorn-sr
        size: 5Gi
    monitoring:
        enablePodMonitor: true