apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: blackbox-exporter
    namespace: blackbox-exporter
spec:
    interval: 10m
    chart:
        spec:
            chart: prometheus-blackbox-exporter
            version: '9.6.x'
            sourceRef:
                kind: HelmRepository
                name: prometheus-community
                namespace: blackbox-exporter
            interval: 10m
    values:
        namespaceOverride: blackbox-exporter
        ingress:
            enabled: true
            className: traefik
            hosts:
                - host: be.biblehome.xyz
                  paths:
                    - path: /
                      pathType: Prefix
        serviceMonitor:
            enabled: true
            targets:
                - name: git-psa
                  url: https://git.psa-europe.com/
                  hostname: git.psa-europe.com
                  interval: 30s
                  scrapeTimeout: 30s
                  module: http_2xx


