---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pugzdec
  namespace: pugzdec
spec:
  encryptedData:
    config.yaml: AgCbL9ngtUZtwdKKsAe5l9C0/9/106sa5QCTyDP6Jq//dY2CU2On3rRQ72D9H+u4SBtiDnF8fUqkK3SKmoljth8IekI/9lgAPXI75y4UtwCuMb/BElcLizSE91GVL0XE3K7/YGt02+hQAlemdRBigF4QQouOQcySjBwla7C7gTbHuQSnOsKAkafnyRIqNuSPzTtKHhn/XZguWH5fpBhdbLCnROAhZ7Qghhp3tlv90Rca7wl6xatOz3H9QBp+CRLkLCg9HbtHli1q3Hz5dFXp5k3mRYA9yS9X6LvZ1ZUbHhzBgfvQanQYYCQp63URWtTzASGoNBf9NyT9qlRtsjIod5noWR9eBRn+Xe6NRhRIdRVsWywBHDMBj9onUcGPWFWu976oOklkeZEW2H+EJTYqkT4gh3XtweItdmvtcLKYhNZ271oDYy/xTTi6IZcLKrYclftQk2gYEG1Ytb1jiAoUulp/rGNBjysRCcfv8X0G8Ii3hQnNQvA/x6StEQFItQs+b1xMHAcJSpAXDytrECIvvrsKDyFokaQLicxOVGn5acPw8+lvfCPzeH/zb4YIz/ueo87mSfZQ3J22Jm+/xJ01Reg06zXbED5pI6LidRo8hoYvnD34IJbG0xNpfQFCzWHnnGDDX5/ZlKRMRKskGUPfuToM4hKkOz0Nkn/IivFYSuBU81gMndmRAhBfHVVC+oJEOLjJye07T1GCytWz3a5G5dSY622zta8n8fgVPyHHDm2QC4QJKQizwEoyXHFiKccYYRYeFcG5uiSIVjaFUyroJP6ETyVKZSxTpXpCKeulkAHhwT9X3bUGiW2wyo87jS4+mpdah8F+WhyElyO9w9H2xMzsQHFjBcG1AC5lETs/kMhiYSUdVKxoBNeH4oj1eDYeBaXJ0MzW3jis6kCIIevfEDQL1I0T+AG3zvpfk1DR+Yxtocdsq+RHIEAQCkvg/0Z76gvu3VxCVjzqqPUifrhDdsU8yXvORA==
  template:
    metadata:
      creationTimestamp: null
      name: pugzdec
      namespace: pugzdec
    type: Opaque
