apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pugzdec
  namespace: pugzdec
spec:
  encryptedData:
    config.yaml: AgBeM6tHoWrRVSw1HOM1st22o93X09bBJjLBo7shSORuS61+DhKgrFdBoHmsIZyCYf0Gcq0K4t3xTyV457oBdV5ESPNVkNFmozDUvViMb14+wj+62/s7D2g2dbhoA9M8BE4JovKWNyICMdi4xeU+ERqD/htol//cs1TYiJ6S7WYPScwaqFvTHk72ijh5rfhjexgpxAaW4+uOKLMpGSyE/AQj9BNeVRRQJ8FOZ2u9xb1ZWg7f439UmfhFPwgS0y4WjyVVYEIRGBPpo6utqkSW53uAP8Q2LGeHdikjrZSuuiqCvKfnq40zEmtlwSRorD9KdPmJ8yWXjGtvhDWxaayWemYNZe3Lo/Tvfbpmj2zmLNsX/Z/MP5WAPCTjBatD3j3D1zOe8uOoNRLkqJXVvIBv1l3OdX0CU+bmqojbpLw09j8+V1VkDHuVww0MZByJvbpkP9jHuWf1twQpDeDECCHqz2LFqMCcmNzAOrnkDDslH0ZxJD9ROhvNVJF48irAh3YI4DehlOPS3gcpeFUhbJWQcu5tV2W7pa1PtrkkxEk04NMv08DnW58pnlpWkKdcy9PhX+VsBanzZW9qZYgTHbW2eh4EGbLGSWfEcfoH3kN1zyHdZNprqpGtphMM9/TvLa9i2nT/hteUx6qWO84Pbz9Mh53KSaa0nCRD0KTeF/zptxpuehDjpXF37Qz9StB8RvPSInoujLq2Irn3YQIhyRaaea2S64EzMgjHSav+muPqfpzuCxSLrSu0mbdayK3Zw4Nff+zW9g3jUj3gG34lhAAzZnbHgbXnPc1rQNztGFy/EHDdHxDU26skidvV8tvc8nQ3y2NNp9cMVlr26o1YOT7S8Ru2q1cYOOZqz6Drzlz5dsNDiKsQgDkNTMuZehJJ0SOfjcMB0QWr9FTvx5BWnzeFunrtY3Z0tJrlKGlXxmqLTaMPa18AHTCr8Fvqvg==
  template:
    metadata:
      name: pugzdec
      namespace: pugzdec
    type: Opaque
