apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pugzdec
  namespace: pugzdec
spec:
  encryptedData:
    config.yaml: AgC2wXuxcwK0VjHyoLklY5YXRDX5vjDSO/enWkkaS5Z4+oZ1Ys/CitrdG2lOS616AiWBL20pul+H25FnM3us7/3E5WeIq1E2YW1aOmv/NXou2oaDprUyjs/Va7gc44jhHT8E6LO08F+RR+6WHQidd9tX1k/MGpsqbGwQMB2ojAVjsF1Su3PYzEVTFaUcnIcoc8Du/xAleVFyASku19Vd/8QEpMF3EUlPVgbSUECY3NET4ZQ4I7ZLla7f2fjNmY2cw4usfD5xfJ5/UrshFn9EJvYzJJYfLlfk1EJrWYraTOAZ4CBamWCPQSNJmBKLAAFA9vSAX4Q/FdPykaN/RBjvO3xsH78sqt3n0jV5DG0fkXB1C2KsU2ENaGGkS8O5SMT4fnkjvRYPsFSTMjMbaXop/HYdvk29HcGkxJWmgYL/OMuLFUNjTiQFjr+dJis1T7BqYjvKqqnQUaoLtdowsoFAQL/oIqeRQTvCzCd61mShFqX+JfcyDSzg6FVhM3hnJrzUud/lGZL58d5KFszgSUn/cGPb4DJnGtSXT4vMLXVLyTjDpSM6mFV5rLX3pbDRaBOMslUuZGscA3vhHSEw6VCDWx0n9Uc1Z4JMfQygQZUqUorSjBVyL/5PS0tD1N62W33/RKtk3hfcPrQ/jEQbYp6VtFxbe0TW7RqgPBHI3KJkyA6xl4zV32IwNG6iP/lvEjSdWW0aEH0NeYNB/eNMXAhOlHn1MyZofB09pj1WVfVW3qsxCsAt6PjB79tXPzKi7Ozd93E++T9azj6RULKXwtVBx9tGPqIiJDuChlczTBVxldb8FC/iQHujbQIV+kH7dlBdu1lMfX/izYKXupgqd6/DfPm264WZjhSjHPuns0M5j2Dm0MV/flrckbi8Pkdn1R5L6U2yDXg1bwfF/MXlh4z1fGG1vuoh1WdiyqsrVNyVmPMv9fT9W0YdjAWrJ3XU1hFsnctIa1SbBa4Tss5VE6CxsWHvFfyZhg==
  template:
    metadata:
      name: pugzdec
      namespace: pugzdec
    type: Opaque
