apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pugzdec
    namespace: pugzdec
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '4.2.6'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "pugzdec"
        deployment:
            resources:
              limits:
                memory: 2048Mi
                cpu: 2
              requests:
                memory: 128Mi
                cpu: 0.1
            enabled: true
            reloadOnChange: true
            env:
              HTTP_PROXY:
                value: "http://192.168.2.60:7890"
              HTTPS_PROXY:
                value: "http://192.168.2.60:7890"
              NO_PROXY:
                value: "localhost,127.0.0.1,10.0.0.0/8,.svc,.cluster.local,192.168.0.0/16"
            volumes:
                config:
                    secret:
                        secretName: pugzdec
            volumeMounts:
                config:
                    mountPath: /config
            image:
                repository: bibletoon/pugzdec
                tag: 0.0.11
            containerSecurityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
        service:
            enabled: true
        ingress:
            enabled: false
