apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: wildcard-bibletoon-xyz
    namespace: kube-system
spec:
    secretName: wildcard-bibletoon-tls
    issuerRef:
        name: cloudflare-issuer
        kind: ClusterIssuer
    dnsNames:
        - "*.bibletoon.xyz"
        - "bibletoon.xyz"