apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: wildcard-bibletoon-xyz
    namespace: kube-system
spec:
    secretName: wildcard-bibletoon-tls
    issuerRef:
        name: cloudflare-issuer
        kind: ClusterIssuer
    dnsNames:
        - "*.bibletoon.xyz"
        - "bibletoon.xyz"
    secretTemplate:
        annotations:
            reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
            reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "authentik"
            reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
            reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "authentik"