apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare-issuer
    namespace: cert-manager
spec:
    acme:
        email: alex8.ivanov@gmail.com
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: cloudflare-isuuer-key
        solvers:
            - dns01:
                  cloudflare:
                      apiTokenSecretRef:
                          name: cloudflare-api-token-secret
                          key: api-token