apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
    name: default
    namespace: kube-system
spec:
    certificates:
        - secretName: wildcard-biblehome-tls
    defaultCertificate:
        secretName: wildcard-bibletoon-tls