apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: supabase
    namespace: supabase
spec:
    interval: 10m
    chart:
        spec:
            chart: supabase
            version: '1.0.x'
            sourceRef:
                kind: HelmRepository
                name: supabase
                namespace: supabase
            interval: 1h
    values:
        db:
            enabled: true
            livenessProbe:
                exec:
                    command:
                        - pg_isready
                        - -U
                        - postgres
                initialDelaySeconds: 3
            image:
                tag: 15.6.1.115
            persistence:
                enabled: true
                storageClassName: "longhorn"
                size: 10Gi
                accessModes:
                    - ReadWriteOnce
        studio:
            image:
                tag: 20240819-375aacf
            environment:
                STUDIO_DEFAULT_ORGANIZATION: "Bibleorg"
                STUDIO_DEFAULT_PROJECT: "Bibleproject"
                SUPABASE_PUBLIC_URL: https://supabase.bibletoon.xyz/
                NEXT_PUBLIC_ENABLE_LOGS: "true"
            livenessProbe:
                httpGet:
                    path: /api/profile
                    port: 3000
                initialDelaySeconds: 3
        auth:
            image:
                tag: v2.159.2
            environment:
                API_EXTERNAL_URL: https://supabase.bibletoon.xyz
                GOTRUE_SITE_URL: https://supabase.bibletoon.xyz
                GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
                GOTRUE_MAILER_AUTOCONFIRM: "true"
                GOTRUE_SMTP_ADMIN_EMAIL: "alex8.ivanov@gmail.com"
                GOTRUE_SMTP_HOST: "smtp.gmail.com"
                GOTRUE_SMTP_PORT: "587"
                GOTRUE_SMTP_SENDER_NAME: "no-reply@supabase.bibletoon.xyz"
        realtime:
            livenessProbe:
                httpGet:
                    path: /
                    port: 4000
                initialDelaySeconds: 3
        storage:
            persistence:
                enabled: true
                storageClassName: "longhorn"
                size: 5Gi
                accessModes:
                    - ReadWriteOnce
            livenessProbe:
                httpGet:
                    path: /status
                    port: 5000
                initialDelaySeconds: 3
        improxy:
            persistence:
                enabled: true
                storageClassName: "longhorn"
                size: 5Gi
                accessModes:
                    - ReadWriteOnce
            livenessProbe:
                exec:
                    command:
                        - imgproxy
                        - health
                initialDelaySeconds: 3
        kong:
            environment:
                KONG_LOG_LEVEL: info
            ingress:
                enabled: true
                className: "traefik"
                annotations: []
                hosts:
                    - host: supabase.bibletoon.xyz
                      paths:
                          - path: /
                            pathType: prefix
        analytics:
            livenessProbe:
                httpGet:
                    path: /health
                    port: 4000
                initialDelaySeconds: 3
        vector:
            enabled: false
        meta:
            image:
                tag: v0.84.0
        functions:
            image:
                tag: v1.58.1
    valuesFrom:
        - kind: Secret
          targetPath: secret.jwt.anonKey
          name: jwt
          valuesKey: anonKey
        - kind: Secret
          targetPath: secret.jwt.serviceKey
          name: jwt
          valuesKey: serviceKey
        - kind: Secret
          targetPath: secret.jwt.secret
          name: jwt
          valuesKey: secret
        - kind: Secret
          targetPath: secret.db.username
          name: db
          valuesKey: username
        - kind: Secret
          targetPath: secret.db.password
          name: db
          valuesKey: password
        - kind: Secret
          targetPath: secret.db.database
          name: db
          valuesKey: database
        - kind: Secret
          targetPath: secret.analytics.apiKey
          name: supabase
          valuesKey: analyticsApiKey
        - kind: Secret
          targetPath: secret.smtp.user
          name: smtp
          valuesKey: user
        - kind: Secret
          targetPath: secret.smtp.password
          name: smtp
          valuesKey: password
        - kind: Secret
          targetPath: secret.dashboard.username
          name: supabase
          valuesKey: dashboardUsername
        - kind: Secret
          targetPath: secret.dashboard.password
          name: supabase
          valuesKey: dashboardPassword