apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
    name: traefik
    namespace: kube-system
spec:
    valuesContent: |-
        logs:
            access:
                enabled: true
                addInternals: true
        api:
            dashboard: true
            insecure: true
        image:
            repository: "rancher/mirrored-library-traefik"
            tag: "2.10.7"
        service:
            spec:
                externalTrafficPolicy: Local
        providers:
            kubernetesCRD:
                allowCrossNamespace: true
        ports:
            traefik:
                expose: true
            metrics:
                expose: true
            web:
                redirectTo:
                    port: websecure
                    permanent: true
            websecure:
                middlewares:
                    - error-pages-redirect-middleware@kubernetescrd