apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    namespace: default
    name: allow-local-only
spec:
    ipWhiteList:
        sourceRange:
            - 127.0.0.1/32
            - 192.168.1.0/24
            - 192.168.2.0/24
            - 10.0.0.0/8