apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: issueneter
    namespace: issueneter
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '6.16.1'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "issueneter"
        deployment:
            enabled: true
            reloadOnChange: true
            env:
                CONFIG_PATH:
                    value: /config
            volumes:
                config:
                    secret:
                        secretName: issueneter
            volumeMounts:
                config:
                    mountPath: /config
            image:
                repository: bibletoon/issueneter
                tag: 0.0.11
            containerSecurityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: false
        service:
            enabled: true
        ingress:
            enabled: true
            ingressClassName: traefik-internal
            hosts:
                - host: issueneter.biblehome.xyz
                  paths:
                      - path: /
