apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: joplyn
    namespace: joplyn
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '4.2.6'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "joplyn"
        deployment:
            reloadOnChange: true
            enabled: true
            env:
                - DB_CLIENT: pg
                - APP_BASE_URL: https://joplyn.bibletoon.xyz
                - APP_PORT: 22300
            envFrom:
                - type: secret
                  name: joplyn-config
            image:
                repository: joplin/server
                tag: latest
            containerSecurityContext:
                runAsNonRoot: false
        service:
            enabled: true
            ports:
                - name: http
                  port: 22300
                  protocol: TCP
                  targetPort: 22300
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: joplyn.bibletoon.xyz
                  paths:
                      - path: /