apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: password-salt
  namespace: wakapi
spec:
  encryptedData:
    salt: AgBJuwch4n0QzTI10yg/I3U8HGKAUgowOo729BjnklF/p+LbscrB1mBWxttleLZAqWJKDUIaQqN1mFXJ+Mb0x97GM2PkFEgQVyXctDkE1WuPfuGB5it9gQ0VFShDuSv4qnLjhRanClvFC7+8+7ym0tCT4TaVINfInh5Zbn7ci5LNAiF8AF1EmBSAM6hlHaUPdvysI2WqLlrYXr+DHDzeKKD3S9JLQQCzhyMdvtwb0rBznNoPMK2BNSqolg+0sXCSXUKy14Lye99pi6nE7NE09JukQA0f7TFA0IHHMm0rBGp+qdutOIK7X8nFOMsSP4aTiGi3ub29Tm6nVBtcam66+apg9p/Q5GMRMRW7RLo3zEwLOJrBWHgNUSXOMAD6XXeCIXrlATOwgUuzqIUQtcS61ZLSQsmYnTZn6bpyJnzqnPqHWF8V5Ge+9sCwePlZRHiAIb5iVr6QWS9QRo6nVBVF9plRfVMwg36ON3U4Ym+eEiuSZHtVxftIx8P+1ZWo3mE90pfwzZYYehNjbnOKZDWwNY8n3S9zEfEQ7qnOTvPXxJ2ooXqiDiHbnqrTvZHxJuu7XeuPRqNRtl+QQAZzAHelWYjeOB9loj5lmboZTrbe18RHJjGqqlBbNrJsogxwZlBNOkYigw+0FxtQ3JaxIoEyV3NXtH4vchDfb3mn7wegRWUhKPeqERNVup57E0X403L0f0dbDJYmpDY4Es9R2O4bEKJ408YEwRMEg9pdxlRRpN9/HVRUxTSFDw==
  template:
    metadata:
      name: password-salt
      namespace: wakapi
    type: Opaque
