apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wakapi-pg-backup
  namespace: wakapi
spec:
  cluster:
    name: wakapi-postgres
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
