apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: wakapi-postgres
    namespace: wakapi
spec:
    instances: 2

    storage:
        storageClass: longhorn
        size: 10Gi
    monitoring:
        enablePodMonitor: true