apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: wakapi
    namespace: wakapi
spec:
    interval: 10m
    chart:
        spec:
            chart: wakapi
            version: '1.0.x'
            sourceRef:
                kind: HelmRepository
                name: wakapi
                namespace: wakapi
            interval: 1h
    values:
        serviceAccount:
            name: wakapi
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: wakapi.bibletoon.xyz
                  paths:
                      - path: '/'
                        pathType: Prefix
        persistence:
            enabled: true
            storageClass: longhorn
            size: 3Gi
        wakapi_config:
            env: production
            db:
                dialect: postgres
            security:
                allow_signup: true
    valuesFrom:
        - kind: Secret
          targetPath: wakapi_config.security.password_salt
          name: password-salt
          valuesKey: salt
        - kind: Secret
          targetPath: wakapi_config.db.name
          name: wakapi-postgres-app
          valuesKey: dbname
        - kind: Secret
          targetPath: wakapi_config.db.port
          name: wakapi-postgres-app
          valuesKey: port
        - kind: Secret
          targetPath: wakapi_config.db.host
          name: wakapi-postgres-app
          valuesKey: host
        - kind: Secret
          targetPath: wakapi_config.db.user
          name: wakapi-postgres-app
          valuesKey: user
        - kind: Secret
          targetPath: wakapi_config.db.password
          name: wakapi-postgres-app
          valuesKey: password