apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: pocket-id
    namespace: pocket-id
spec:
    interval: 10m
    chart:
        spec:
            chart: pocket-id
            version: '1.7.6'
            sourceRef:
                kind: HelmRepository
                name: anza-labs
                namespace: pocket-id
            interval: 1h
    values:
        host: id.bibletoon.xyz
        database:
            provider: "postgres"
        ingress:
            enabled: true
            ingressClassName: traefik
            host: id.bibletoon.xyz
            paths:
                - path: /
                  pathType: Prefix
        persistence:
            enabled: true
            storageClass: longhorn
            size: 5Gi
    valuesFrom:
        - kind: Secret
          targetPath: database.connectionString
          name: pocket-id-postgres-app
          valuesKey: uri