apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: redis-password
    namespace: authentik
spec:
    encryptedData:
        password: AgADcdw5cO0cIIyg8LN6hcGN5kLk5PAD11JTHEuDw7sgl4kk7sw4WAN7a79AS1YXP4ZodRwl/iA1iJmbeLV6OIz++eR1DGzsnT6ZlO4PstB3oOYOWzcMjY6XRMWQvXGFsTgnyUfwQRph3nkKTQeslneWM5ILBiW5R2FtMnPb0VlVd3Q1oytBrjAWFrY8BjZzNQgCWB8YRqGU+hofZSpE3DVxq47Mr8zI5lboQ7p8cJOaN/IMRKgZuToTXesV5Rm0ozrQ2N/yRf0R+7844ZnVGsc88v3o4y+RILf4Y0HGcr8SeJwPWj67wRFyMmvZN6jLRdOACii1d/1Lpk0zaQRe7dpVWXElz26PoBcPlBgiame1ZmzsB9FCrY7IhW10x+LlC4ZAyia+hJm4kzMh9lyg8wAqwZ2eYX6Y8rlIQ7/f7QiVQ0mYUxrlw28+BoFw0JokVnzchU0gLpYYYVjuIxlcbUZfY5W7VrDLofNDS91QEZJOu8BfScHIUkBQBwbbnYEeziGdtv8BO2MMr2D2soCXn2/xvdNC4A9DoIHdm5hYY8S+Bq0Vw94P0l3r6fRJkRZWiOFOrBfadfudGWFJcl1+0pDFqcJVyX7KVWw4ajdvpgjwbIsdAgARaY/R+6Wj6ES2jxOuMpmffUUMBGvVPxNTNA3PBSoFiEhcs9DoKIRVvNykjLg675b7Ukb7oWa+dGUrFZYn8ZOK9An5wJjtic8=
    template:
        metadata:
            name: redis-password
            namespace: authentik