apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-secret
  namespace: vaultwarden
spec:
  encryptedData:
    adminToken: AgCLuYi2j525X9sRVT0e2dcTi5KJOBcEfT4AWh9yiq3bWMGQhyHqQ2ggDVoYpveSMRqg2lZCf/IRg6lVGJdJPE4TxrxKBqS9iubo0QQgpOkRWCb5unrkXYfhDegNArhL4HGg8zd2rlRVCXAfzGazojV94Kq59QD0InYExwqYI70Rf26/U581nJW+MqItssVlMkFfbbAqvgPURY4fp/5FBOn5j2Hh+C14Sw7gmY+04IUEZh8JJ5FOisdtrw03NmDM3cwF7mHviG3mLPZuWpK06q/vL7VxsBkROcInkokPFINfhVAAce2FqlDa+Fhfeml+H3B6eBtkHmFyvoiNcHiKMeSodiMmQiVQKuhrq4nBkIwqD2nfLEMeQ7rZSo+XAMGYGRok9/jyXgkUOyLViFrQTUDDlcS5onusfYUEpN8zBbW2jDoBuqHMI5qgRATe4lyGNjSa6WxT8tq6a/f1EQC3rGZxTsA65Ir9YnBD84Ao9miNz9hadlUfjSsIEowkLlRk1/kdOf8X1kU1mZphDunjtbI2TzITk0y10ubO3ge1Ej3JwKHXCjTQjjCiQG8S1Fhr0nVZ3cH/A19vci7QEiUy+TtINl75LXd7I2jOTf+PDpPa92ZSoE7SP5R4rLps9VTkej02uEyL9A7uNoTKiH1t7DygCLVs81gwAdWrXUPzCPdoz/Sd80osd3Ggb52tvHVpIGsPsBJwJaJntI6eagFhXvtR3bWruMQfeCDqQzrFcMOMe4P81QBlk1Wu8Egs72eHKxHBN9XTl84zsROYc/P3fab9502dU4xLjgw=
  template:
    metadata:
      name: vaultwarden-secret
      namespace: vaultwarden
