apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: actual
    namespace: actual
spec:
    interval: 1h
    chart:
        spec:
            chart: actualbudget
            version: '1.8.5'
            sourceRef:
                kind: HelmRepository
                name: community-charts
                namespace: actual
            interval: 1h
    values:
        login:
            method: "openid"
            openid:
                discoveryUrl: "https://id.bibletoon.xyz/.well-known/openid-configuration"
                authMethod: "openid"
                existingSecret:
                    name: "actual-openid"
                    clientIdKey: clientId
                    clientSecretKey: clientSecret
        ingress:
            enabled: true
            className: traefik
            hosts:
                - host: actual.bibletoon.xyz
                  paths:
                    - path: /
                      pathType: ImplementationSpecific
        persistence:
            enabled: true
            storageClass: longhorn
            size: 5Gi