apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: factorio-server-secret
  namespace: factorio
spec:
  encryptedData:
    game_password: AgAFbb9JMWqIp0bDi1l78L4CjV1oeyRddEM9H9YTeN8WC6B3dqe9AEsib3Dc840cXRzSXRbO9s67pwMqq6zd+n5bWZnBkdMgh7hyBkz8OaSUwfj53I62N6ZB+3EqDfFPkglBSR7DLwTLGU32MJ/2TSISv6+C88PnHZ1dLH36x1/irfvSKdc5WuBXK0WcbXUaxCal5hHZqX0DC39ArL6VBclS0u6/fG8riOL94hmrUnKDou4eR8GN+eAuYOxvfD18lkOVO7sT2s/w8jozC+CNHPv8cNwGORG6Kxi68ceZGJNIG1PLNuISDU2MQHbSbJOrK7u0JgoW9qj4cR1dZ8BtJtAq43LiuKw7sRWsP+ghQ0Wewio8Rjdss/pzKzaxxnbHplKrQ8j6agyJYFPB5hFzQyxsw7rDte6K6l9C5Z4zmTomfu46k9mwmvzr2ISlYagT4XRRp5DP6Y5Q6rURySQqX45TKwK0KjtHtiTvNRE3C+RYVjrLYFb2nzHJqpzXJcajqpaDrw2nUcRBc5yzwfCWML145LYIF8gTbK5VrQ2/+s3C62b46OZ6HY/wvT8Qzi44aHNuTQMeudZXZ4NiR3h8s9kpwmWxH8EkxS1uRyKkbB2i73nSbMq5FMKJ+f3FTuFbu6zLslvUih5+koMESHlTgu/mltpAY3HjNZUTEW6biNgk9UnNRQIEQdQimLYMp3pPM0L4qx5LIRKtJrZt
    rconpw: AgBn+WC8BBvSjm3L32OA8qGAQaB4qBMb42elQGKxW2w8YRty1mdBxwE/TVOs44oQuY/S4p7AF/XmCZuhHqgjmDvQX3t8LBsIPj253OKrrpoAM/MLMm0s+/mlIplzJWyDbGpR0Cl1bD8w9PZVqTLzMcfBMJCJ0xsEKTDcYKU8R8jNcnCfg5s8e26g1mPwRV127NB8AQIZ/YPTzA7PJRHXcGNsjD2ySE1OE2iGkLYG5FLKN+mHNmov3YzK4t+2PsD2MLVJuTCrtCs3o8SLCpNvL9yZq5ee4T5biT1sp8M3F5TyYhmQ0ITbSPPcjAAgB5s3EQI8A8dofHNvqvg6TI5vuaq03JWnAPWKdU+mA+IecSBss6Wk5cgrm0vQ23hV8eYsKMsZ42NP2deWqFQxeUflSMhP4xRK/E9XITw9/L2q/bayLoRC9VtlOOm8UGIzhiNswC7OcXYaGP9YEyZuCPwfLEwYFAirp6y6Fugg1iP/Xo9RBp30f2lkOKjSQNtCuSQz0RsE9WDH9jUhxutp/FBwVR71VesOTtpGrX5ewiCGSPU7QcIKrU6ChLZPSjaagyaueVSv6NcWRO8YG9D4rm8rMQTgU0BC37w7e2bYTA0nARIol32nIaeAZ4R4qz0EO4WClKGQ7kuNSWPqOXp97mON1zlR/aRhYt10VbhzE5KG2hXbsAiy/OCxxxQI8Q1PlYbwXI/BvMPW3GLk3zytnWaEPA==
  template:
    metadata:
      name: factorio-server-secret
      namespace: factorio
    type: Opaque
