apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: n8n
spec:
  encryptedData:
    password: AgCHc+UmIwpnTm6cqXUU1mslHayZjfYWNGPcfu1dm3Q6D3N/QgfVRyjcXlFsJu6MnbmMgsWBwYO9x7diqmn5PhVCq64SmKMQr5tztDeB0hjOFOdaX91lep8j6WzD7oaPydrO1S62Ui+PzKsrHmCVklP9uKuvRK6MKAAHCfCJjAerDcgsVhQiwYGwXklhWZWAkjDzPzagUb0AJNUzYlSmOsalcuk7j1HLXKQNDEuby5rX/BSuO34Iq5fnz8VqeEfc4r9jkkQ/MGN9SbEUrJvHZFJX1MJK7OeRzBSnRfNDseP1J+Tdpq3Faoe+6cQX7L0sTw6XuCch3H36aQ9S682vFkAH9q2s/sSUQEqHiHFr1bSXnTbg6hkAGAH4VKH0OrRUyr4xZWeiHTxVQtUSr/ZACbvCLcvsaLOBu7X8sWjG72L6dlSGLP8UFJ1YKX0sEDSNhADvTWedLagSfnYiZT0T3sZdCYTjQgnC1xZtEZcoYEES26Gq1QZKikwxAGssN2xBCSlTnVS6UDz9QLK55UclDal/JzuKb1q1m7kbBIktZTo+Uv1lGf8DUnxfiVO04ntJqKhTiptXabwA0Qxguew6ZTKydR5htINVL3bF/1lgmfar8GaiU2/RMMhw4Chi978DWKNplKw3QJu80qEEQ+UMEU6X5A1TfQIjrU0cN9ku//107L40ntgempwtdb2dFvgw0VZErR4INIq4ZAqcVsrwDCllzGaqL0fo
  template:
    metadata:
      name: redis-password
      namespace: n8n
