apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: n8n
    namespace: n8n
spec:
    interval: 1h
    chart:
        spec:
            chart: n8n
            version: '0.24.x'
            sourceRef:
                kind: HelmRepository
                name: n8n
                namespace: n8n
            interval: 1h
    values:
        image:
            tag: "1.55.3"
        config:
            database: postgresdb
        persistence:
            enabled: true
            storageClassName: longhorn
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: n8n.bibletoon.xyz
                  paths: ['/']
    valuesFrom:
        - kind: Secret
          targetPath: config.postgresdb.database
          name: n8n-postgres-app
          valuesKey: dbname
        - kind: Secret
          targetPath: config.postgresdb.host
          name: n8n-postgres-app
          valuesKey: host
        - kind: Secret
          targetPath: config.postgresdb.user
          name: n8n-postgres-app
          valuesKey: user
        - kind: Secret
          targetPath: secret.postgresdb.password
          name: n8n-postgres-app
          valuesKey: password