apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mealie-oidc
  namespace: mealie
spec:
  encryptedData:
    clientId: AgC6pCx7Q5zZFcV4DhnkMLjgWOw9su7KBCdAU9NNfTjAcWXNOH9hhvNe4M/xgeQ5bh5UAGyOOqFeZA8jfHVyX01chBXh+2i3oRmLtDc8rond9TuNBfw56eO1mUi9K2k/B/rsIfHD+bMfKvjaxAGbyKXr2Iyljs73WkfM4Crx+A6EBw5wNBUWbk3Ak4wg4EI/v4TH+0GDPS4ir0r4PqFiwR7KjVbwlHptQqzXiotTn7KyY/+i/JQAIzHJyx1aJMPEP6FHQa4AVGJM/qhYJAuhC3x6Y6S7QbyUwh+3UM8g+lhNZB+9K7Qmob+za0EUr2knCdr4f2b60ZGpUTk+TXZvDZCq9KCu3v7Uyf7HDubnPZGIC5gt6+WWRSDRUCx0JVBAkY22j0+P7XC/4NEO1FcZhBk9JY7XyAGSew5M4EkOUbggNM7MlrmzNuzkByXJXiKA4I5Uza+NLVlpzyd1AHqKhdZLzeFVW6y77ddpyD+5lcQwl29mWodedmhyTXnBhfyyD/1GqMzm3cUlQSZaKdAimwQduUsR7LxXPE6ssy51r92jOgltCAnRU39ONtOzSi7au+mnY7kwsbhAkvMHPBFRY6e9fthidf6T9FqWVC7lllXRAhhTjUH8XI1Ei5n7yn/Ueu+wisyt8i/3jW3OgfT+dKrfQWiMxx5uq722XgZHI2KHSFIHKWuFqvpzXFj4wqWW+oXTfZbFC5WqPH8B5McWcXKHu/YZW7o5DtXPLhNXEtKOetXHFc0=
    clientSecret: AgBeebDjC4/E0vXFI/ge8hfEMJnCoEWVXv1p15iSVNfDDfg9CxTXHewhiDnbKCwJ1IivYuqLzZdzn2hRnd3x6praQfA9GU0EfAialuZyXFtkAdc2e5gbV0t7TzZP2te8nOfRwIOuwHXOYGFkSn6DELG4RSNlJS945ZAmanBIfwF4mVM8mqBGS7A5RQ8iTSQzuV4my82B6n62SY1+Wh4aj/y6i8sFWElkCP7s/ZUFKuTWCBQFO7HmrHMc9Ny76V+WapS38XYsMQ7o38ETtnGjhrUE/AGBS9ESJzbG4IfjTkBykcetpGiXC+BlAvY/aaG9mlW1LuiFDIiLZ0tTOUDonX5Eznr22xxkytO9OmGKTZwTRtVlM1eLCATFpIEQ2n1hybcdehYHY5qw3Lt8DeVkAC9js6aho0SDCHoeYhSZ2dau6/l7WA4HYSp3kgEiWQkiIpItDWC+KoCe0hoQpjUlCBZuLv+Joa4TrzsWp9YT9n69+GGSluOJfxWXKFrPLrgPdLzhsIQcJ0jk5SvwFStYlvo2BgultTZnCOhsUw/51iCkLuiLo3OuU7nIw37s9vMUs62AQRMUZgVieOR3fAqpekMmpNSiSIKwPaPWnK4rDSYcyXHYI3E5fGB3dBVbU8/aYLAkGeYDc5OJllwYYPpkl9nBPb9yd/20ReXkMNjaXler+bjgG4ZUuFCx+aPPZuqFD654skUVw4s+ePJEvvIshNkJMQ4hMpDjJxLiHa3C0w97lg==
  template:
    metadata:
      name: mealie-oidc
      namespace: mealie
    type: Opaque
