apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: mealie
    namespace: mealie
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '6.14.0'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "mealie"
        deployment:
            enabled: true
            reloadOnChange: true
            env:
                ALLOW_SIGNUP: 'false'
                ALLOW_PASSWORD_LOGIN: 'false'
                OIDC_AUTH_ENABLED: 'true'
                OIDC_CONFIGURATION_URL: 'https://id.bibletoon.xyz/.well-known/openid-configuration'
                OIDC_AUTO_REDIRECT: 'true'
                OIDC_ADMIN_GROUP: 'mealie_admins'
                OIDC_REMEMBER_ME: 'true'
                OIDC_USER_CLAIM: 'preferred_username'
                OIDC_NAME_CLAIM: 'display_name'
                TZ: Europe/Moscow
                DB_ENGINE: postgres
                BASE_URL: 'https://mealie.bibletoon.xyz'
            image:
                repository: ghcr.io/mealie-recipes/mealie
                tag: v3.9.2
            containerSecurityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: false
        service:
            enabled: true
            ports:
              - port: 9000
                name: http
                protocol: TCP
                targetPort: 9000
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: mealie.bibletoon.xyz
                  paths:
                      - path: /
    valuesFrom:
        - kind: Secret
          targetPath: deployment.env.POSTGRES_DB
          name: mealie-postgress-app
          valuesKey: dbname
        - kind: Secret
          targetPath: deployment.env.POSTGRES_SERVER
          name: mealie-postgress-app
          valuesKey: host
        - kind: Secret
          targetPath: deployment.env.POSTGRES_USER
          name: mealie-postgress-app
          valuesKey: user
        - kind: Secret
          targetPath:: deployment.env.POSTGRES_PASSWORD
          name: mealie-postgress-app
          valuesKey: password
        - kind: Secret
          targetPath:: deployment.env.POSTGRES_PORT
          name: mealie-postgress-app
          valuesKey: port
        - kind: Secret
          targetPath:: deployment.env.OIDC_CLIENT_ID
          name: oidc-secret
          valuesKey: clientId
        - kind: Secret
          targetPath:: deployment.env.OIDC_CLIENT_SECRET
          name: oidc-secret
          valuesKey: clientSecret
