apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: mealie
    namespace: mealie
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '6.14.0'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "mealie"
        deployment:
            enabled: true
            reloadOnChange: true
            env:
                ALLOW_SIGNUP:
                 value: 'false'
                ALLOW_PASSWORD_LOGIN:
                 value: 'false'
                OIDC_AUTH_ENABLED:
                 value: 'true'
                OIDC_CONFIGURATION_URL:
                 value: 'https://id.bibletoon.xyz/.well-known/openid-configuration'
                OIDC_AUTO_REDIRECT:
                 value: 'true'
                OIDC_ADMIN_GROUP:
                 value: 'mealie_admins'
                OIDC_REMEMBER_ME:
                 value: 'true'
                OIDC_USER_CLAIM:
                 value: 'preferred_username'
                OIDC_NAME_CLAIM:
                 value: 'display_name'
                TZ:
                 value: Europe/Moscow
                DB_ENGINE:
                 value: postgres
                BASE_URL:
                 value: 'https://mealie.bibletoon.xyz'
                POSTGRES_DB:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-postgress-app
                      key: dbname
                POSTGRES_SERVER:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-postgress-app
                      key: host
                POSTGRES_USER:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-postgress-app
                      key: user
                POSTGRES_PASSWORD:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-postgress-app
                      key: password
                POSTGRES_PORT:
                  valueFrom:
                    secretKeyRef:
                      name: mealie-postgress-app
                      key: port
                OIDC_CLIENT_ID:
                  valueFrom:
                    secretKeyRef:
                      name: oidc-secret
                      key: clientId
                OIDC_CLIENT_SECRET:
                  valueFrom:
                    secretKeyRef:
                      name: oidc-secret
                      key: clientSecret
            image:
                repository: ghcr.io/mealie-recipes/mealie
                tag: v3.9.2
            containerSecurityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: false
        service:
            enabled: true
            ports:
              - port: 9000
                name: http
                protocol: TCP
                targetPort: 9000
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: mealie.bibletoon.xyz
                  paths:
                      - path: /
