apiVersion: v1
kind: Service
metadata:
  name: nas
  namespace: nas
spec:
  type: ClusterIP
  ports:
    - port: 30027
      targetPort: 30027
      protocol: TCP
      name: nc
    - port: 30041
      targetPort: 30041
      protocol: TCP
      name: im
