kind: Service
apiVersion: v1
metadata:
  name: nas-service
  namespace: nas
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30027