apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: error-pages
    namespace: error-pages
spec:
    interval: 1h
    chart:
        spec:
            chart: error-pages
            version: '1.2.x'
            sourceRef:
                kind: HelmRepository
                name: k8s-at-home
                namespace: error-pages
            interval: 1h
    values:
        image:
            tag: 3.3.0
        env:
            TEMPLATE_NAME: lost-in-space
            SHOW_DETAILS: "false"