apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: reflector
    namespace: reflector
spec:
    interval: 10m
    chart:
        spec:
            chart: reflector
            version: '9.1.x'
            sourceRef:
                kind: HelmRepository
                name: emberstack
                namespace: reflector
            interval: 10m