kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: affine-storage
  namespace: affine
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 1Gi
  storageClassName: "longhorn"