apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: affine
    namespace: affine
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '4.2.6'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "affine"
        deployment:
            reloadOnChange: true
            enabled: true
            initContainers:
                affine-migration-job:
                  image: 'ghcr.io/toeverything/affine-graphql:stable'
                  command: ['sh', '-c', 'node ./scripts/self-host-predeploy.js']
                  envFrom:
                    - secretRef:
                        name: affine-config
            envFrom:
                - type: secret
                  name: affine-config
            volumes:
                affine-storage:
                  persistenceVolumeClaim:
                    claimName: affine-storage
                affine-config:
                  persistenceVolumeClaim:
                    claimName: affine-config
            volumeMounts:
                affine-storage:
                  mountPath: /root/.affine/storage
                  subPath: storage
                affine-config:
                  mountPath: /root/.affine/config
                  subPath: config
            image:
                repository: ghcr.io/toeverything/affine-graphql
                tag: stable
            containerSecurityContext:
                readOnlyRootFilesystem: false
                runAsNonRoot: false
        service:
            enabled: true
            ports:
                - name: http
                  port: 3100
                  protocol: TCP
                  targetPort: 3100
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: affine.bibletoon.xyz
                  paths:
                      - path: /