kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: affine-config
  namespace: affine
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 10Gi
  storageClassName: "longhorn"