apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
    interval: 10m
    chart:
        spec:
            chart: homepage
            version: '2.0.2'
            sourceRef:
                kind: HelmRepository
                name: jameswynn
                namespace: homepage
            interval: 1h
    values:
        ingress:
            main:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - host: 'biblehome.xyz'
                      paths:
                        - path: /
                          pathType: Prefix
        config:
            services:
                - Monitoring:
                    - Grafana:
                        href: https://grafana.bibletoon.xyz
                        description: Kubernetes observability
                        icon: grafana.svg
            bookmarks:
            widgets:
                - resources:
                    backend: kubernetes
                    expanded: false
                    cpu: true
                    memory: true
                - kubernetes:
                    cluster:
                        show: true
                        cpu: true
                        memory: true
                    nodes:
                        show: true
                        cpu: true
                        memory: true
            settingsString: |
                title: Homepage
                headerStyle: boxed
                layout:
                    Monitoring
            kubernetes:
                mode: 'cluster'
        env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: biblehome.xyz