apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: firefly
    namespace: firefly
spec:
    interval: 1h
    chart:
        spec:
            chart: firefly-iii
            version: '1.9.2'
            sourceRef:
                kind: HelmRepository
                name: firefly
                namespace: firefly
            interval: 1h
    values:
      persistence:
        enabled: true
        storageClass: longhorn
        storage: 1Gi
      config:
        env:
          TZ: "Europe/Moscow"
      secrets:
        env:
          APP_PASSWORD: ''
      ingress:
        enabled: true
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: traefik-oidc@kubernetescrd
        className: traefik
    valuesFrom:
        - kind: Secret
          targetPath: secrets.env.DB_PASSWORD
          name: firefly-postgres-app
          valuesKey: password
        - kind: Secret
          targetPath: secrets.config.DB_HOST
          name: firefly-postgres-app
          valuesKey: host
        - kind: Secret
          targetPath: secrets.config.DB_DATABASE
          name: firefly-postgres-app
          valuesKey: dbname
        - kind: Secret
          targetPath: secrets.config.DB_USERNAME
          name: firefly-postgres-app
          valuesKey: user
        - kind: Secret
          targetPath: secrets.config.DB_PORT
          name: firefly-postgres-app
          valuesKey: port
