apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram
  namespace: monitoring
spec:
  encryptedData:
    token: AgCwGxI06vJaR4phWMe+r7X0skteYONDrsJI4LEIhXnu+CJoD/a+MdTgcwN9KkLcyl1WU7RXzs+FqCn+NRDx21AozzvANPRUHLjc8o14ubvQOWZ/ggw4Sp0giIpZ/0Qe2jEIhpgYQ23o3vETW2C7NiKLxjG6QQGoBDD5m7JMJA3bNvRrnY501o/TA0AxM93sY360v44QzciQgdxXzvxZcDn9CVK63Z6Ed1FRb8IHhKsv6Iv3y4xGRWLH0r7iVAV+zVIBhoCQNq1DIVUObeem/fvT9adRz9aYgECH3LpaP4adfhLE7Wc3cALHGLMVI1hcpbUDGVjwXjQIG2dZ3sar9NNo17vptg3AtGMtsRScqkZEdrnuN2Q1o0HVb32GGBDpU+3MzgMQ6RZ6QVUPViiYzOXbMobx8gtqjB1Z7sjD6qUmBe3Vlz2RAI6CkWKBHDb2aLqaCd2A1V015NdLvEJO1iSbdQFchPfPg8Q7RcBGMa8f8AhRXcaidwDUbt63iK3IBYw62bJCFMsbVuY9EYJKxvfRJ1r1n4wLMHYcEdUZnS2BXbeuvMxC87694HfybZmhh7KkVpb/4WISxSl0rdSg7GeIO13zifHvnWSjzHElKh50OWdEHIAqiqPxtcoUCkTkYIkV7SCPqf4MhATxB2zDwhpUWbldOs2BPyZifCLWiM9GNQ7AusuBv1tZC+N5nOcdniJ582owN9Wm52FXsL6jl0EOlVcknxOIVZbQFHWOh3ql1QNE9CxdI5Ehzdtp6VTI
  template:
    metadata:
      name: telegram
      namespace: monitoring
