apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: rss-bridge
    namespace: rss-bridge
spec:
    interval: 10m
    chart:
        spec:
            chart: rss-bridge
            version: '0.5.2'
            sourceRef:
                kind: HelmRepository
                name: rss-bridge
                namespace: rss-bridge
            interval: 1h
    values:
        image:
            repository: rssbridge/rss-bridge
            tag: sha-de9aef0
        persistence:
            config:
                enabled: true
                storageClass: longhorn
                size: 1Gi
        ingress:
            main:
                enabled: true
                ingressClassName: traefik-internal
                hosts:
                    - host: rss-bridge.biblehome.xyz
                      paths:
                          - path: /
