apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg-barman-cloud
    namespace: cnpg
spec:
    interval: 10m
    chart:
        spec:
            chart: plugin-barman-cloud
            version: '0.3.1'
            sourceRef:
                kind: HelmRepository
                name: cnpg
                namespace: cnpg
            interval: 1h
