apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg
    namespace: cnpg
spec:
    interval: 10m
    chart:
        spec:
            chart: cloudnative-pg
            version: '0.23.x'
            sourceRef:
                kind: HelmRepository
                name: cnpg
                namespace: cnpg
            interval: 1h