apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: outline
    namespace: outline
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '4.2.6'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "outline"
        deployment:
            reloadOnChange: true
            enabled: true
            envFrom:
                - type: secret
                  name: outline-config
            image:
                repository: outlinewiki/outline
                tag: 0.82.0
            containerSecurityContext:
                readOnlyRootFilesystem: false
                runAsNonRoot: true
                runAsUser: 1001
            resources: {}
        persistence:
            enabled: true
            mountPVC: true
            mountPath: '/var/lib/outline/data'
            storageClass: longhorn
        service:
            enabled: true
            ports:
                - name: http
                  port: 3100
                  protocol: TCP
                  targetPort: 3100
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: outline.bibletoon.xyz
                  paths:
                      - path: /