apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: blog
    namespace: blog
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '6.14.0'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "blog"
        deployment:
            enabled: true
            reloadOnChange: true
            image:
                repository: bibletoon/bibleblog
                tag: 0.0.2
            containerSecurityContext:
                readOnlyRootFilesystem: true
                runAsNonRoot: true
        service:
            enabled: true
            ports:
                - port: 80
                  name: http
                  protocol: TCP
                  targetPort: 80
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: bibletoon.xyz
                  paths:
                      - path: /
