apiVersion: v1
kind: Secret
metadata:
    name: config
    namespace: stickerizer
stringData:
    values: |-
        {
            "bot": {
                    "token": "",
                    "bufferChatId": 0
                },
            "app": {
                    "logLevel": "debug"
                }
        }
  