apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config
  namespace: stickerizer
spec:
  encryptedData:
    values: AgCAbSm9XHmk+J/b4qlqrBRgZEytgpn7tqC0WDKPS9TWMo7QQqkjhgvh9mdxMbMdRZ7INeBZwnJ0ghg/5d1zynYnOMus2Ad6U64QXz+z9Kq47BM1uhAP0TncINyhcUiHoOhgIGG1zGeMF6wgqiNFDNITLfgkfFSmEi3LJspsWIYCGMdIiBPAs4hKx7Gds+gE86Zrz77/NpeJW2wRYFTvope0cfy/CWvJPVMseIXDBHXb0xiqaOaEA2x6cMgt7Z3tE4+Zw2Z7R9OZSvLMi+dndOWeaq8EAEmqfe/r8f/6BdHMCDsfB/Q5mn4AAWL43bCUXclNs5FNT0bPgFgAwI+B+qolzgYSkAdvYwTqXl3n3tXBmXIF2+cIcVYYQJFOQc2I5zztSvyunknGkh/eh/KGqxpZwFovGMx3oTGE9i9Kz8zg+m85CqN9zSkRD++c6a0yfahfMrbwkSjSqwYl5GPaIazAlv44grtH6vvzjZdV1ezDgbKKthuRI1QRsSMxT3MriO1/6+6WANzWobCinjRTQEuSoKg6Wxh3wxVnweUKLoizIm5LnnodIQJlLt175d5+v9AtuLWYYRXyw4Z/gdQAPes9tl18/1QA4n0alYY0CINZz8Nc3ZNAoTLEgQUBCbuK1XFPbtVDPfifS+4Oz1s5YlVs9TXQ8wQRzMe5KWaKcdnSllxLiIWRpNGit/HVERH3RetZ9OiiirT2MscgTgW86m5RN63pqPeDXBFpN4iBvGYkemlG2NGvZbDNbEWgfaC2IFFBjMZLAmZ6TSLqNBh5SZqIiYuYsc3nwgxIIcVpv+9sKgvZY1HAuuOjttzfM5QU/YL+28yXLJ61OKOuDzA0N330YgZ7OI0lOmIYkkoFK2lcAxeaakswnKw5mFTYvG2WnmAVZPExgBvTIhZKty6EfeP9hf3PDnXFBDFVAqWCL4sC/JxPbSPuRwcNLye2TN2EEQ==
  template:
    metadata:
      name: config
      namespace: stickerizer
