apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config
  namespace: stickerizer
spec:
  encryptedData:
    values: AgBVg21P6LjzxOkZZHaGVuJJ2ddhd2QIIhY1DN8RP8IxjzkgJGgBX80W2NiF1fPYssrB2+zmihvg3znR8OOaqzZSJrJYxStYEX7NODYEjInaRio1JhrF2Nx+58qbMhh/xKr+R13wSq6EMCurxRHuyicT9N2Ju/f6CrHdb0TL1OG0Jfhilyhr111IfVv47C/6rwuEA5ZXNJX2/7Vbr16GL7LV2LZBtbzR0QtmadpOf1ygM6hqDcl9+rPACy5dwPmum5WfSgZM4yJ+1SBZdH37ZFetqsOdBamHyh9VwygTuwEXP+4bB4ZZK4YrLAH/kzP2viJBTVISoFxc1wqacCrJLI4lg4RZ0Ko7pzysm1FXw0nLcCjdQk8tqEXf4LIr+zF5JjhynoYW/LRwBowDkG3qHbtBYdvUP6UYpJdRn7aVoUPOSBB+x/qs84WL7hcdy1TWcb4Lq85wkC7BV+kCvo7QE3KV4GJukByAE4FmKjdIJ2o1R+qNY2YA0Ea6vhVlZfOG/GA0icsPZyFVpmTORzoQ/hQ3EPPrTdwu9qrG3be0hf3Y4mKGTyBM4Z1Z7mpy2IsD/lq+tk2M3xgIsSi1+Ja3iBCt14zFK8341JFO1XEgtU63DKZ75FmtrSwbSXEHK8ppAA5DL7i7ht0TXFmCuAq1QG709eYe9B1WO2N0rQ4cMLt3GfGjIY4n9ByQ4o0/UJuDwR/UQtqLN2qCZGVamzs0UNHDjxWergtJ7SSt8Bp6613T4jFa+5EOGZhrY8nANa/pkb02kKUTgxb31WK0BMER/RBh/hQ8pdxoAeC4gBBZtJhAEhrOA679ngXPFOSI08ht+JhLOImguvUJw36X7t8Ek29y7eYEIKpiPvgRhJyGVpL0gbmWy6oWNa3nBw==
  template:
    metadata:
      name: config
      namespace: stickerizer
