apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja-oidc
  namespace: vikunja
spec:
  encryptedData:
    clientId: AgB4rIlbUezNX3bCS8wmUeclUpRvLgFHLwz6La8O0FQz4UPryajxRI0n9dYpyIgD5aaItNcrjFAQRDMEEeUj5Uhf9AOUeVc6AeLSv54Cuu8ZeUTqpD4eICF6DKjBo0v+JQhK0lJyGpntZY5m8c7ES8CiRwksNmzl7+9962xif0kwslbPH2KWNgNOBVyjIVBjAQ8q5WYCj1LKEjxrVdyhthiLZRWsaFY1LWzwWxrDTzd2EMK5AvAWdzefCHqkxmmd2sNIdD/c3CFbtPJKXSt9Bvd9vm5YinaH2zNsqJElgd8HziXlvFaNhu+JaooPY3iqdNS4DX3jZUwEy94nAlyuHCp3+BvAtWtj7yGaxQ6B63R7fsIovvvi9+BtP19ctzUd5elnXN0B1OtJmnR3d6fpO3HcJNlWJrhBCCQSEa66Or2YJ3e35WGJDSN0njOEq2TBiU4kwwT7+1tBHy17u3ZRsZ9jkBEhaImuEH/8gNk1ipcVK86WFSXxS9RS5hupCUMi/Zy/jNThtsUVDHu8hKILqm1zUKMZ/LPLtOhXWK1s8VVOl85Q3irGLHPzcbF8HRItP0Ek5rtHgpAYb0tY2RPdr8NofnOKX7MKDFHWY0nD5LKXzxaOy1uoTO7oYTeykNEJV9e9kVSMSn43xF83hqJvXZ2bUrN9zXaqdnrMfJ1wtZDqo39srwNCkMB4HG51acMwRISNnXA4b7fx2VNg7nybRAfSRn2FkvWSxbxqU3/+niML/QDoT/k=
    clientSecret: AgBmyFGLvNzsLllgTnvhUbtXdekYaA59fgtZQJ2zWjqsSwqkdiIFhQUG/XwSa7UyclCewiJRBk/43c4GcMQErz3VCQUKeeee2D7AhXC/vn464gfBmZI3qzXFGx9H4QL8GC5V35ih2kDaqLhc8VNMwznql1gWLKAz50zJ5rVp0y+lmxoznLiw3IyD9LfRnuIPjyAagBo9XdISxeUAiiOVyO/GBVJB87lWFVNPmc8Fq2jsE4etsN+SieXGna1jmZqkQ47lfuTToUr4rjKKsLpxQz5rrpatAX6pP7JsKM1P9+awXmkJaSWDh5uBU1jm+rSSmvqaAiVA6ESevptd+Yst57gHzwWrXtK2/wNDlYaNwJBzNFSvjT0/YNAZZPdnmTEBWHJe5hJu4kDNHlJI9TbmmRqAjvz3N+dkimOlSN5pAX1SF8Wp64xHVz+sDMGqZlRj5XbQSDAjA/r98/yrc5KQh4sVlL4DrlG55WOlDKIQUm56IYhm9L+vsf4l0nQ5g3kDOCooYchNZhc63WY557UJqbiSvK84HoFKvQRfUrKX31O5t+aP3CjAZiEglX/8Aor1LEVZWAzsA/QTWdvczvxukcsCfTQvzdzNO/rk4UXhU7SpMMDc2tcrs3DocP+hNpxiig3uRXe4S0dXiZo0sVTZfK1fOdcj4PZPsqdCY0dHblAT/dBanuzwpPBlFsWvsovCf37ejgyaWqPb8wNKTtocSZz4zJoehVZbve8r3WzcALJsCg==
  template:
    metadata:
      name: vikunja-oidc
      namespace: vikunja
    type: Secret
