apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: factorio
    namespace: factorio
spec:
    interval: 1h
    chart:
        spec:
            chart: factorio-server-charts
            version: '2.5.x'
            sourceRef:
                kind: HelmRepository
                name: factorio
                namespace: factorio
            interval: 1h
    values:
        rcon:
            type: ClusterIP
            passwordSecret: factorio-server-secret
        service:
            type: LoadBalancer
            port: 34197
            annotations:
                metallb.universe.tf/loadBalancerIPs: 192.168.1.102
        image:
            tag: 2.0.69
        persistence:
            enabled: true
            size: "10Gi"
            storageClassName: "longhorn"
        factorioServer:
            save_name: "Server"
        serverPassword:
            passwordSecret: factorio-server-secret
        server_settings:
            name: Bibletoon's server
            visibility:
                public: false
            require_user_verification: true
