apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: joplin-postgres
    namespace: joplin
spec:
    instances: 3

    storage:
        storageClass: longhorn-sr
        size: 15Gi
    monitoring:
        enablePodMonitor: true

    bootstrap:
      recovery:
        source: joplin-backup-source

    externalClusters:
      - name: joplin-backup-source
        plugin:
          name: barman-cloud.cloudnative-pg.io
          parameters:
            barmanObjectName: s3-store
