apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: longhorn
    namespace: longhorn
spec:
    interval: 10m
    chart:
        spec:
            chart: longhorn
            version: '1.8.0'
            sourceRef:
                kind: HelmRepository
                name: longhorn
                namespace: longhorn
            interval: 10m
    values:
        ingress:
            enabled: true
            host: "longhorn.biblehome.xyz"
            tlsSecret: wildcard-biblehome-tls
            annotations:
                traefik.ingress.kubernetes.io/router.middlewares: default-allow-local-only@kubernetescrd