apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: bookstack-mariadb
  namespace: bookstack
spec:
  rootPasswordSecretKeyRef:
    name: bookstack-mariadb-pass
    key: password
  storage:
    size: 5Gi
    storageClassName: longhorn-sr
  replicas: 3
  replication:
    enabled: true
  service:
    type: ClusterIP
  metrics:
      enabled: true