apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: bookstack-mariadb
  namespace: bookstack
spec:
  rootPasswordSecretKeyRef:
    name: bookstack-mariadb
    key: password
  storage:
    size: 5Gi
    storageClassName: longhorn-sr
  image:
    repository: mariadb
    tag: "11.3"
  replicas: 3
  service:
    type: ClusterIP
  metrics:
      enabled: true