apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: bookstack
    namespace: bookstack
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '4.2.6'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "bookstack"
        deployment:
            reloadOnChange: true
            enabled: true
            env:
                TZ:
                    value: "Europe/Moscow"
                APP_URL:
                    value: "https://bookstack.bibletoon.xyz"
                APP_DEFAULT_DARK_MODE:
                    value: "true"
            envFrom:
                - type: secret
                  name: bookstack-db-config
            image:
                repository:  lscr.io/linuxserver/bookstack
                tag: latest
            containerSecurityContext:
                runAsNonRoot: false
                readOnlyRootFilesystem: false
            persistence:
                enabled: true
                mountPVC: true
                mountPath: "/config"
                storageClass: longhorn
                name: "bookstack-data"
                storageSize: 5Gi
        service:
            enabled: true
            ports:
                - name: http
                  port: 80
                  protocol: TCP
                  targetPort: 80
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: bookstack.bibletoon.xyz
                  paths:
                      - path: /