apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: kitchen-owl-postgres
    namespace: kitchen-owl
spec:
    instances: 3
    storage:
        storageClass: longhorn-sr
        size: 5Gi
    monitoring:
        enablePodMonitor: true
    plugins:
      - name: barman-cloud.cloudnative-pg.io
        isWALArchiver: false
        parameters:
          barmanObjectName: s3-store
