apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: wg-easy
    namespace: wg-easy
spec:
    interval: 10m
    chart:
        spec:
            chart: wg-easy
            version: '0.1.3'
            sourceRef:
                kind: HelmRepository
                name: wg-easy
                namespace: wg-easy
            interval: 10m
    values:
        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/loadBalancerIPs: 192.168.2.103
        environmentVariables:
          WG_HOST: bibletoon.xyz
          WG_CONFIG_PORT: 8228
        ingress:
          enabled: true
          className: traefik-home
          hosts:
            - host: wg.biblehome.xyz
              paths:
                - path: /
                  pathType: ImplementationSpecific
        volume:
          enabled: true
          className: longhorn-bkp
          size: 1Gi
    valuesFrom:
      - kind: Secret
        targetPath: environmentVariables.PASSWORD_HASH
        name: wg-password
        valuesKey: passwordHash
