apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: wg-easy
    namespace: wg-easy
spec:
    interval: 10m
    chart:
        spec:
            chart: wg-easy
            version: '0.1.x'
            sourceRef:
                kind: HelmRepository
                name: wg-easy
                namespace: wg-easy
            interval: 10m
    values:
        service:
            type: LoadBalancer
            annotations:
                metallb.universe.tf/loadBalancerIPs: 192.168.1.102
        environmentVariables:
            PASSWORD:
        image:
            versionOverride: "15"
        volume:
            enabled: true
            className: "longhorn"
            size: 100m
        ingress:
            enabled: true
            className: traefik
            annotations:
                traefik.ingress.kubernetes.io/router.middlewares: default-allow-local-only@kubernetescrd
            hosts:
                - host: wg.biblehome.xyz
                  paths:
                      - path: /
                        pathType: Prefix
