apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: wg-easy
    namespace: wg-easy
spec:
    interval: 1h
    url: https://raw.githubusercontent.com/hansehe/wg-easy-helm/master/helm/charts