apiVersion: v1
kind: ConfigMap
metadata:
    name: alertmanager-templates
    namespace: prometheus-stack
data:
    telegram.tmpl: |
        {{ define "__alerts_list" -}}
        {{ range . }}
        {{if ne (index .Labels "alertname") "" -}}
        {{ if eq .Status "firing" }} 🔴 {{ else }} 🟢 {{ end }}
            {{- if ne (index .Labels "severity") "" -}}
                <u><b>[{{ index .Labels "severity" }}]</b></u> {{ end -}}
        <b>{{ index .Labels "alertname" }}</b> 🕙 {{ .StartsAt.Format "15:04:05    🗓️ 2006-01-02" }}{{ end -}}
        {{ if len .Annotations }}
        <i>Annotations:</i>
            {{ range .Annotations.SortedPairs -}}
            - {{ .Name }}: {{ .Value }}
            {{ end -}}
        {{ end }}
        {{ if len .Labels -}}
        <i>Labels:</i>
            {{ range .Labels.SortedPairs -}}
            - {{ .Name }}: {{ .Value }}
            {{ end -}}
        {{ end }}
        <i>Value:</i> {{ .ValueString }}
            {{- if gt (len .GeneratorURL) 0 }}<a href="{{ .GeneratorURL }}">source</a>  |  {{ end }}
            {{- if gt (len .SilenceURL) 0 }}<a href="{{ .SilenceURL }}">🔕 silence</a>  |  {{ end }}
            {{- if gt (len .DashboardURL) 0 }}📁 <a href="{{ .DashboardURL }}">dashboard</a>  |  {{ end }}
            {{- if gt (len .PanelURL) 0 }}<a href="{{ .PanelURL }}">panel</a> {{- end -}}
            --------
        {{- end -}} {{- /* range */ -}}
        {{- end -}} {{- /* define __alerts_list */ -}}

        {{ define "__telegram.title" -}}
        {{ if ne (index .CommonLabels "severity") "" }} <u><b>{{ index .CommonLabels "severity" }}</b></u> {{ end -}}
        {{ if ne (index .CommonLabels "alertname") "" -}}
            [{{ index .CommonLabels "alertname" }}]
        {{- end -}}{{- /* define __telegram */ -}}
        {{- end -}}

        {{ define "telegram.message" }}
            {{ if gt (len .Alerts.Firing) 0 }}
            🚨 <b>ALARM</b> (#{{ .Alerts.Firing | len }})
            {{- template "__alerts_list" .Alerts.Firing }}{{ end -}}
            {{ if gt (len .Alerts.Resolved) 0 }}
            ✅ <b>RESOLVED</b>{{ template "__telegram.title" . }} (#{{ .Alerts.Resolved | len }})
            {{- template "__alerts_list" .Alerts.Resolved }}{{ end }}

        <a href="{{ .ExternalURL }}">📲 Grafana</a>
        {{- end -}}
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
    name: alertmanager
    namespace: prometheus-stack
spec:
    replicas: 3
    configSecret: alertmanager-main
    configMaps:
        - alertmanager-templates
    containers:
        - name: alertmanager
          env:
              - name: TELEGRAM_TOKEN
                valueFrom:
                    secretKeyRef:
                        name: telegram
                        key: token
    storage:
        volumeClaimTemplate:
            spec:
                storageClassName: longhorn-sr
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 5Gi
    externalUrl: https://alerts.biblehome.xyz
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: alertmanager
    namespace: prometheus-stack
spec:
    ingressClassName: traefik-internal
    rules:
        - host: alerts.biblehome.xyz
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: alertmanager-alertmanager
                            port:
                                number: 9093
