apiVersion: v1
kind: ServiceAccount
metadata:
    name: prometheus
    namespace: prometheus-stack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: prometheus
rules:
    - apiGroups: [""]
      resources:
          - nodes
          - nodes/metrics
          - services
          - endpoints
          - pods
      verbs: [get, list, watch]
    - apiGroups: [""]
      resources: [configmaps]
      verbs: [get]
    - apiGroups: [networking.k8s.io]
      resources: [ingresses]
      verbs: [get, list, watch]
    - nonResourceURLs: [/metrics, /metrics/cadvisor]
      verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: prometheus
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: prometheus
subjects:
    - kind: ServiceAccount
      name: prometheus
      namespace: prometheus-stack
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
    name: prometheus
    namespace: prometheus-stack
spec:
    replicas: 3
    serviceAccountName: prometheus
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    probeSelector: {}
    probeNamespaceSelector: {}
    scrapeConfigSelector: {}
    scrapeConfigNamespaceSelector: {}
    ruleSelector: {}
    ruleNamespaceSelector: {}
    retention: 5d
    retentionSize: 45GB
    storage:
        volumeClaimTemplate:
            spec:
                storageClassName: longhorn-sr
                accessModes: ["ReadWriteOnce"]
                resources:
                    requests:
                        storage: 50Gi
    alerting:
        alertmanagers:
            - name: alertmanager-alertmanager
              namespace: prometheus-stack
              port: web
    externalUrl: https://prometheus.biblehome.xyz
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: prometheus
    namespace: prometheus-stack
spec:
    ingressClassName: traefik-internal
    rules:
        - host: prometheus.biblehome.xyz
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: prometheus-prometheus
                            port:
                                number: 9090
