s3:
    access_key: ENC[AES256_GCM,data:2bLicV/7h0wlf3tCbe81bRFX42rh7rY7x24=,iv:4gsPrKnW579HFj8IP6i2Y7RRk9IeL+1h86rCG5/QVUE=,tag:a0kYnDqJLNSHiKMLIyI8ug==,type:str]
    secret_key: ENC[AES256_GCM,data:fwzERm+PlXaR0UM3s/BjUDZDGRG0+5D8ih6IhPs22tsEZ1B8M++z1wPb71VNfvcHmUuE4vZ+SX+Z5VvLQ/d86w==,iv:hNccKns8VFOtd7bSCsEz24hu7aoa2TGpEq5yZ/lup/Q=,tag:x3OKyDJ+m7vN8XntGecWBQ==,type:str]
proxmox:
    api_token: ENC[AES256_GCM,data:VZ0aGfRLmm19sJodNYZO11jx8DJ6VP0BGwj5UrN0BFmsvpoSrnEPFTelqxZWB2fEFXE=,iv:Gil1ego83rjldpqQlUrwycbmlPMis9w05sODoZgTEHY=,tag:Tp6uFiHwVEwOKojA4u7hVw==,type:str]
    user:
        username: ENC[AES256_GCM,data:9GXrFP5t3Tsp,iv:rcHuTzKryv8K3nFbTweAvJeFL8PPBjinNinuE9p9GUc=,tag:DpqM1KpoP406fXP9Ujv0VA==,type:str]
        password: ENC[AES256_GCM,data:GYTRuK2FksrIzA==,iv:7kLtfnb7cDwEakB3iDAmbKxR1Fm1HcIwklNFBd3zJtI=,tag:O1tJ1G2imZfViUQwp8cnuQ==,type:str]
sops:
    age:
        - recipient: age1gpz7qfvvzgersnms3gncl09frdkuyu4yhnzrd95h8n5lez0aw5jsnvlpy0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobDcvbWFNU0ltK2RQMUlU
            REZrVlk2K0o1UVBRQlhOYUYvMFlrancwTHpBCkI0MGFsWC9OOCt0WHRjR09mN1Vp
            QlI1cDJwRG5PZzU0UWdyeTFMNHZxcUEKLS0tIDV6eFg1dE1qOXFaWFg0TFVsN1Nk
            TVhwYzkxRDV0b3F4c2FOMW5STDRsZE0KLIj7zybMk3fJdV6Yi59mKYA5+zE6pf4G
            vOAc3CFHvNzs3lnOZJB6CmQofGtiQrnbRXl2dzA/8Vcp/Sb7vPn7eQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T16:09:11Z"
    mac: ENC[AES256_GCM,data:HesmO1hVhLmz6YvgaRrbDD3z5bP/P1XrW5Kk8Rx28klUht7Iqe6V2j8Suy35pp64VUezttP/TpKE7QOuYkYOrPlnlEmMY5L282CVycTjhJqcIfW8TSFJxni4/LdJgYzVm0caYd6y3SdQ9K7ZMGSR/w5P/WHC+y1O+7Z1IztrkTk=,iv:rTWvNJ1kJS3t1UR9EWFQxH/K8Mdd5E4uHtRVTGlD+LI=,tag:+zzIE2qi3NOuqxZjaELpNg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
