apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: grocy
    namespace: grocy
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '4.2.6'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "grocy"
        deployment:
            enabled: true
            env:
                TZ:
                    value: "Europe/Moscow"
            image:
                repository: linuxserver/grocy
                tag: latest
            containerSecurityContext:
                runAsNonRoot: false
                readOnlyRootFilesystem: false
        service:
            enabled: true
            ports:
                - name: http
                  port: 80
                  protocol: TCP
                  targetPort: 80
        ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
                - host: grocy.bibletoon.xyz
                  paths:
                      - path: /