apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: loki
    namespace: loki
spec:
    interval: 10m
    chart:
        spec:
            chart: loki-stack
            version: '6.27.x'
            sourceRef:
                kind: HelmRepository
                name: grafana
                namespace: loki
            interval: 1h
    values:
        gateway:
            service:
                type: LoadBalancer
                loadBalancerIP: 192.168.2.102
        loki:
            auth_enabled: false
            persistence:
                enabled: true
                size: 10Gi
                storageClassName: longhorn
        promtail:
            tolerations:
                - operator: Exists

