apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: memos-pg-backup
  namespace: memos
spec:
  cluster:
    name: memos-postgres
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
