apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: config
  namespace: colette
spec:
  encryptedData:
    appsettings.Production.yaml: AgB0b3uBz7MLlBAoIk5Ajlwd2S0gVzjHEDCybzKa5qk4LleVrbstil1z8/BmPXGYRc7farJ4Ve4BgYDHYmaM2qipuZgqfEvYq4jwijVbZVLqbLhuc5+AGlS+1wzWLXVJdGccebjPt6ABF372dgr8syPshO0ZNyavvJtskszUTcGQbmTraZxsYFnRcyTa00ofld2hpr1I2LJniHHr/9d3scgwP56x2D0G4tth8lsdaL8Q5N1tlDCCsbh4NefETnJn5zff/3mKAM9u3YDZAd690ZLFnuL38Y5ImvyA+Tc3geoq75XNxz4wmobEVO/a4IIFut+FlAEkxy2f+0bJ78M1JpYV6aEZG/ru3ehGYu+KK0FMMX3AqNg0ALHVsZI0G8gVM7fITliZLCr4i5St4P/lwJwbbekLnQIr92DmfM0FFN6UU3OyXHqX0SCzd9jBpId0bfW3l5afF+Ht5f053p8ShHhOTd6bbQbyh70nBCbM/JXEnQ9bOHQwjgS/OjWSg2aIOm7p/LILMgctBus97hK6TCfyW+5Es0v5EKLOfl4v3k0GM4yQhu97SNd5J6ekPjwIergrUygwOOAAVMOZO+ZEouMxJfkSq9J2o2WOuPXT21r06zAUwuxViN8sV5Ou2F0Eu1dMPTwj0nccyI1pJJ1AKa1vWwCOLGi4sJeSUGBS51e3xL0ZTw0PLiRcnUGp5P8inQa8fbaROKqkEWAM/yuNWzU6iBOyObSeHfzdzHhC4EyULN+s6ImvJ/O/+GyoQslppeTYWXjgY1iYAZuebBTvMxxljqC0YgPEn+YEYTa97lm4648X72dtoKc+h6a8rbaimF1mE8xPvcMnZ/sAND72Ku8Ge2tdX35AhQXDoP2g6hlbjPOazRLxy9vL6ItSQXXgUqcqHdpsjgExHNgfr3mdcxmEzCQgifywHs06i1betw5UFFFH2tuc+3nN2rhhSw+Rfqc2StHWtDGI/QAHcoGuMA78CyMlYPV3/Dk52aS0eYE5s1Z/tvtq+PbvXznOX/hnZNAqPQC9fVwqfYbrkVYN4uABqy/Y7zbZtUmHj9aWsvlv+4gR8YV6VInb9NxSW9zHYum7tHY3fZS3oEUZPOlKqd5f75GBjf5T0Ye1tPvaB3wXqDTJnIPML57Orzl8Hl1RokZolp4MlZfZZaVYtKcM4eLiNg==
  template:
    metadata:
      name: config
      namespace: colette
