apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: colette-postgres
    namespace: colette
spec:
    instances: 2

    storage:
        storageClass: longhorn
        size: 5Gi
    monitoring:
        enablePodMonitor: true