apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: authentik-postgres
    namespace: authentik
spec:
    instances: 3
    storage:
        storageClass: longhorn-sr
        size: 10Gi
    monitoring:
        enablePodMonitor: true