apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: authentik
spec:
  encryptedData:
    password: AgAt2rOgM16wz5gLooyXnGKeVdebUAYg2gSfMr3n3jXUObbvvwBT4LpqQyck0y0VX+etH76rPo2hcG91pYNxs32c9bJ/9AWnewD/ccJHkov0ZPV0PRDFei0Hy8YJNKdwDz7Av7oDk0nAW9xmLvyWHIxFWJN7+BmjyfNIlnWdLTKnPiN0fm9mSJFzSBR6hFkAjePHxprROblpTt8XQMZmiMEXsoOmf11Vx+rENQRzg7Gb48eqASqVP72Iv7XfcNC5hGnXfg0K/r2YHXsSER/bgYWNL7kf5ceKnKIxqn2KOBipX4SOAbFcbLCE9AxjX9BYKBzzB+Tkp3PF9r6BgeTwNW5C7Xko4DbuH/XSRXLBhkOaH7c4EOEOhyHnO+53ZIp5NblK89WxsNw5CNmKWbt1VJm5d6RHpZOMDJ9EnbxFX48WL0eU+Hjp6M+JKP941hmU0qmvwuGnTH6lmsSfTeVipRIgnNyZ9PiOLJ5SUDOUfBccn9IVjInqRbFVQ3c5XAlGXZewj9+PcjdxHI1iWDhYlJzJ1pb27llwJBUXtd2lY+xZkTtWsCy8XJUqvFe3K5bFCiLHvzg0CDre1vl0uqRa3+UxsXo0ksySKarAHfuCwpV4GH/KgHMeYLjZsX5WkbqNEvmPO7SBshxZ9rn3A52Iy6NTal/YIChX56nztqVDA76j3PlwtUmh8ShzuYpWEPMCAAKPIkB4eLTg+qkLTazm3TcbSkM=
  template:
    metadata:
      name: redis-password
      namespace: authentik
