apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: authentik
    namespace: authentik
spec:
    interval: 10m
    chart:
        spec:
            chart: authentik
            version: '2024.6.x'
            sourceRef:
                kind: HelmRepository
                name: authentik
                namespace: authentik
            interval: 1h
    values:
        global:
            env:
                - name: AUTHENTIK_SECRET_KEY
                  valueFrom:
                      secretKeyRef:
                          name: authentik-key
                          key: key
        authentik:
            redis:
                host: "authentik-redis-master"
                password: file:////redis-creds/password
            postgresql:
                host: file:////postgres-creds/host
                password: file:///postgres-creds/password
                user: file:///postgres-creds/user
                name: file:///postgres-creds/dbname
        server:
            metrics:
                enabled: true
                serviceMonitor:
                    enabled: true
                    namespace: monitoring
            ingress:
                enabled: true
                ingressClassName: traefik
                hosts:
                    - auth.bibletoon.xyz
            volumes:
                - name: redis-creds
                  secret:
                      secretName: redis-password
                - name: postgres-creds
                  secret:
                      secretName: authentik-postgres-app
            volumeMounts:
                - name: redis-creds
                  mountPath: /redis-creds
                  readOnly: true
                - name: postgres-creds
                  mountPath: /postgres-creds
                  readOnly: true
        worker:
            volumes:
                - name: redis-creds
                  secret:
                      secretName: redis-password
                - name: postgres-creds
                  secret:
                      secretName: authentik-postgres-app
            volumeMounts:
                - name: redis-creds
                  mountPath: /redis-creds
                  readOnly: true
                - name: postgres-creds
                  mountPath: /postgres-creds
                  readOnly: true
        postgresql:
            enabled: false
        redis:
            enabled: false


