apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: vaultwarden-pg
    namespace: vaultwarden
spec:
    instances: 3
    storage:
        storageClass: longhorn-sr
        size: 10Gi
    monitoring:
        enablePodMonitor: true
