kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: trillium-data
  namespace: trilium
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: 5Gi
  storageClassName: "longhorn"