apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: trilium
    namespace: trilium
spec:
    interval: 10m
    chart:
        spec:
            chart: trilium 
            version: '1.3.0'
            sourceRef:
                kind: HelmRepository
                name: trilium
                namespace: trilium
            interval: 1h
    values:
        controllers:
          main:
            containers:
              trilium:
                image:
                  repository: triliumnext/notes
                  tag: v0.90.8
                  pullPolicy: IfNotPresent
        persistence:
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: trillium-data
        ingress:
          main:
            enabled: true
            hosts:
              - host: trilium.local
                paths:
                  - path: /