apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: trilium
    namespace: trilium
spec:
    interval: 10m
    chart:
        spec:
            chart: trilium
            version: '1.3.0'
            sourceRef:
                kind: HelmRepository
                name: trilium
                namespace: trilium
            interval: 1h
    values:
        controllers:
          main:
            containers:
              trilium:
                image:
                  repository: triliumnext/trilium
                  tag: v0.101.3
                  pullPolicy: IfNotPresent
                env:
                  TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERBASEURL: 'https://id.bibletoon.xyz'
                  TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHISSUERNAME: 'PocketId'
                  TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHBASEURL: 'https://id.bibletoon.xyz/.well-known/openid-configuration'
        persistence:
          data:
            enabled: true
            type: persistentVolumeClaim
            existingClaim: trillium-pvc
    valuesFrom:
        - kind: Secret
          targetPath: controllers.main.containers.trilium.env.TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTID
          name: trilium-oidc
          valuesKey: clientId
        - kind: Secret
          targetPath: controllers.main.containers.trilium.env.TRILIUM_MULTIFACTORAUTHENTICATION_OAUTHCLIENTSECRET
          name: trilium-oidc
          valuesKey: clientSecret
