apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: yamtrack
    namespace: yamtrack
spec:
    interval: 10m
    chart:
        spec:
            chart: application
            version: '4.2.6'
            sourceRef:
                kind: HelmRepository
                name: stakater
                namespace: application
            interval: 1h
    values:
        applicationName: "yamtrack"
        deployment:
            enabled: true
            reloadOnChange: true
            env:
                TZ: Europe/Moscow
                URLS: https://yamtrack.bibletoon.xyz
            envFrom:
              - type: secret
                name: secrets
            image:
                repository: ghcr.io/fuzzygrim/yamtrack
                tag: 0.24.11
            containerSecurityContext:
                readOnlyRootFilesystem: false
                runAsNonRoot: false
        service:
            enabled: true
        ingress:
            enabled: true
            ingressClassName: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-oidc@kubernetescrd
            hosts:
                - host: yamtrack.bibletoon.xyz
                  paths:
                      - path: /
