apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: grafana-postgres
    namespace: grafana
spec:
    instances: 3

    storage:
        storageClass: longhorn-sr
        size: 5Gi
    monitoring:
        enablePodMonitor: true
    bootstrap:
        recovery:
          backup:
            name: grafana-pg-backup-20260411000000
    plugins:
      - name: barman-cloud.cloudnative-pg.io
        isWALArchiver: false
        parameters:
          barmanObjectName: s3-store
