apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBKp3fto5WvPu9f6Uu0+Hz0KJ1ziZGNaEagA3Sgz7Ts0Nwq0WD4D4ESm9DHK4NyKAofWh2oATVWQXqwtGlV0VH5ugBwxJfQyoHmg36xC4VG0TliTxbGp/Un5F6HsbEvv+5ZClFecOKGpPsXiGjwPRk9vnFs/XcQLqhPHs1n0UnG70lvuPfs9taInt5x7Q3ib07dxM80Ko4IKW4dkSv8mPoIZdqdNkzZ8Iit66p7q2k83x7/KcXgzoVf1ohYBdPigIh3f9qNuC6gH90m8yl+6bUO3gAFQNCSC6sh6TNcVNGgbTFxX/x7uRH+ZlIquiC1JX5179ZEgbbuhjcVHjr36RU3mPpmvNIqP0SvRBrVAJKdhSVr3/XQED0ZyIknM8jOud77Q4r0uIpqjxzSKlnVD3+gYcywBCh/uV/8AbHg37HNkRUUJN+Y7+u0oMU3qWAbQKGy6Rhy5MOK5X2JidN2r9XzhXDNqlj/991Bwzcbd0UcnuNo/I/7e/uDlQX3//U4HTF9lSlr/K/2jCe6845s0efp1rqnKL37dJCL1SEK60rKrWUmavmkrcCMWvL7iOhJH9IpQDlXsM2qGgZffJnPbNvR8dIS+aAQf0SCMQE675qa0IHICng5f0udny139M6MYeEvxCxHz5yvGXgRz8QSoMgIc4/5BhSO2ctdqpyu2J79Jc+ju1D0XAuXG71iSB3+6D/c82HVmXbNi1m3sfQ9HFysgvQeu2kCA4IzPEvIBeu/aR/V5AV0fTaW
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque